spring:
  application:
    name: vehicle-renting
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/vehicle_renting}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
